### ISSUE TITLE
simplify the validator

### ISSUE THREAD

**Issue by backbone87** [fluoresceco/validate-embedded#1]
the validator can be simplified by running the subvalidation in the parent context:

``` php

        /* @var $context ExecutionContextInterface */
        $context = $this->context;
        $context->getValidator()
            ->inContext($this->context)
            ->validate($value, null, $constraint->targetGroups);
```

this adds the violations directly to the existing violations

**Comment by jaikdean** [comment]
I tried this method originally, but one of my embedded objects implements `GroupSequenceProviderInterface` to do conditional validation on some of the fields. If I use the simplified validator you suggest then only validators with the groups explicitly listed in `$constraint->targetGroups` (or `$constraint->embeddedGroups` in my code) are run.

I've not dug into where and how GroupSequenceProviders work, so it may still be possible.

**Comment by jaikdean** [comment]
It's amazing what a fresh look will do, I've figured out why my testing was failing, and the code you've suggested does work.
