### ISSUE TITLE
Combine with group closure on parent form

### ISSUE THREAD

**Issue by rvanlaak** [fluoresceco/validate-embedded#2]
In our scenario the form has four fields, lets call them "scenario", `Book`, `Author` and "reason". Important: `scenario` and `reason` should always be validated and the other two are entities. Based on the scenario we want to validate the fields of the `Book` or `Author` entity types.

I did hope that your validator would work together with the `validation_groups` closure as documented on: http://symfony.com/doc/current/form/data_based_validation.html

Will the validator be able to also validate these entities if they did not define `validation_groups` themselves? We have other pages that should be able to add `Books` too without having to define these groups.

**Comment by jaikdean** [comment]
Apologies for the slow reply. As I understand it, this should work as you want it to with no further work. Are you having a problem with it?
